name: database_repository
description: Dart package which manages the authentication domain.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  intl: ^0.16.1
  firebase_core: ^0.6.0
  cloud_firestore: ^0.15.0
  firebase_storage: ^6.0.0