name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  firebase_core: ^0.6.0
  firebase_auth: ^0.19.0+1
  equatable: ^1.2.5